# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

info_about_network <- function(nodes_id, nodes_type, edges_from, edges_to, types_name, types_count) {
    .Call(`_sbmrcpp_info_about_network`, nodes_id, nodes_type, edges_from, edges_to, types_name, types_count)
}

